use crate::item::ParsedItem;
use std::fmt::Write;

/// Render the facade `.rs` that replaces the original file: preserves inner
/// attrs and the original `use`s, declares each generated sub-module, re-
/// exports them, and inlines any "primary" items whose bucket name matches
/// the file stem (these would otherwise round-trip through `<stem>/<stem>.rs`).
pub fn render_facade(
    inner_attrs: &str,
    facade_uses: &[&ParsedItem],
    facade_primary: &[&ParsedItem],
    sub_modules: &[String],
) -> String {
    let mut buf = String::new();
    if !inner_attrs.is_empty() {
        buf.push_str(inner_attrs);
        buf.push_str("\n\n");
    }
    buf.push_str("// Auto-generated by r2factor. Manual edits will be overwritten on next split.\n\n");

    for it in facade_uses {
        buf.push_str(&it.source);
        buf.push('\n');
    }
    if !facade_uses.is_empty() {
        buf.push('\n');
    }

    for m in sub_modules {
        if m == "tests" {
            let _ = writeln!(buf, "#[cfg(test)]\nmod {m};");
        } else {
            let _ = writeln!(buf, "mod {m};");
        }
    }
    if !sub_modules.is_empty() {
        buf.push('\n');
    }

    for m in sub_modules {
        if m == "tests" {
            continue;
        }
        let _ = writeln!(buf, "pub use {m}::*;");
    }
    if !sub_modules.iter().all(|m| m == "tests") {
        buf.push('\n');
    }

    // Primary items live in the facade itself — they're the main thing this
    // file is "about", and pushing them into <stem>/<stem>.rs would create
    // an awkward duplicated path.
    let mut primary_sorted: Vec<&&ParsedItem> = facade_primary.iter().collect();
    primary_sorted.sort_by_key(|it| it.line_start);
    for it in primary_sorted {
        buf.push_str(&it.source);
        buf.push_str("\n\n");
    }
    buf
}
