use super::FACADE_MARKER;
use crate::item::{ItemId, ParsedItem};
use crate::promote::{CrossImport, add_pub_super, lift_impl_methods};
use std::collections::BTreeSet;
use std::fmt::Write;

/// Render the facade `.rs` that replaces the original file: preserves inner
/// attrs and the original `use`s, declares each generated sub-module, re-
/// exports them, and inlines any "primary" items whose bucket name matches
/// the file stem (these would otherwise round-trip through `<stem>/<stem>.rs`).
pub fn render_facade(
    inner_attrs: &str,
    facade_uses: &[&ParsedItem],
    facade_primary: &[&ParsedItem],
    sub_modules: &[String],
    path_prefix: Option<&str>,
    promote: &BTreeSet<ItemId>,
    impl_lifts: &BTreeSet<ItemId>,
    facade_imports: &BTreeSet<CrossImport>,
) -> String {
    let mut buf = String::new();
    if !inner_attrs.is_empty() {
        buf.push_str(inner_attrs);
        buf.push_str("\n\n");
    }
    buf.push_str(FACADE_MARKER);
    buf.push('\n');
    buf.push_str(
        "// Auto-generated by r2factor. Manual edits will be overwritten on next split.\n\n",
    );

    for it in facade_uses {
        buf.push_str(&it.source);
        buf.push('\n');
    }
    if !facade_uses.is_empty() {
        buf.push('\n');
    }

    // Order matters: `#[macro_use] mod macros;` MUST precede any sibling
    // `mod` that calls a macro, since `macro_rules!` uses textual scoping
    // — the macros are imported into the parent scope only after this
    // declaration, and propagate forward to subsequent `mod` items.
    for m in sub_modules {
        if m == "macros" {
            emit_mod_decl(&mut buf, m, path_prefix, &["#[macro_use]"]);
        }
    }
    for m in sub_modules {
        if m == "macros" || m == "tests" {
            continue;
        }
        emit_mod_decl(&mut buf, m, path_prefix, &[]);
    }
    for m in sub_modules {
        if m == "tests" {
            emit_mod_decl(&mut buf, m, path_prefix, &["#[cfg(test)]"]);
        }
    }
    if !sub_modules.is_empty() {
        buf.push('\n');
    }

    // Skip `pub use macros::*;` — `macro_rules!` are not items and aren't
    // re-exportable that way. They reach siblings via `#[macro_use]` above.
    for m in sub_modules {
        if m == "tests" || m == "macros" {
            continue;
        }
        let _ = writeln!(buf, "pub use {m}::*;");
    }
    if sub_modules.iter().any(|m| m != "tests" && m != "macros") {
        buf.push('\n');
    }

    // Imports the facade itself needs for `pub(super)` items in sub-buckets
    // that its primary code references. `pub use {m}::*;` above only re-
    // exports `pub` items, so without these explicit lines the bare names
    // would fail to resolve at facade scope.
    if !facade_imports.is_empty() {
        for imp in facade_imports {
            for cfg in &imp.cfg_attrs {
                let _ = writeln!(buf, "{cfg}");
            }
            let _ = writeln!(
                buf,
                "use {src}::{name};",
                src = imp.source_bucket,
                name = imp.name
            );
        }
        buf.push('\n');
    }

    // Primary items live in the facade itself — they're the main thing this
    // file is "about", and pushing them into <stem>/<stem>.rs would create
    // an awkward duplicated path.
    let mut primary_sorted: Vec<&&ParsedItem> = facade_primary.iter().collect();
    primary_sorted.sort_by_key(|it| it.line_start);
    for it in primary_sorted {
        if promote.contains(&it.id) {
            buf.push_str(&add_pub_super(&it.source));
        } else if impl_lifts.contains(&it.id) {
            buf.push_str(&lift_impl_methods(&it.source));
        } else {
            buf.push_str(&it.source);
        }
        buf.push_str("\n\n");
    }
    buf
}

fn emit_mod_decl(buf: &mut String, module: &str, path_prefix: Option<&str>, attrs: &[&str]) {
    for attr in attrs {
        let _ = writeln!(buf, "{attr}");
    }
    if let Some(prefix) = path_prefix {
        let _ = writeln!(buf, "#[path = \"{prefix}/{module}.rs\"]");
    }
    let _ = writeln!(buf, "mod {module};");
}
