use crate::item::{ItemId, ItemKind, ParsedItem};
use std::collections::BTreeMap;

/// Render one `<bucket>.rs` body. Items are emitted in original source order
/// so the diff is easy to follow; `use` items are skipped here because they
/// already live in the shared prelude block at the top.
pub fn render_sub_file(
    ids: &[ItemId],
    by_id: &BTreeMap<ItemId, &ParsedItem>,
    use_prelude: &str,
) -> String {
    let mut buf = String::new();
    buf.push_str("// Auto-generated by r2factor. Manual edits will be overwritten on next split.\n\n");
    // Sibling refs flow through the facade's re-exports.
    buf.push_str("use super::*;\n");
    if !use_prelude.is_empty() {
        buf.push_str(use_prelude);
        buf.push('\n');
    }
    buf.push('\n');

    let mut sorted_ids: Vec<ItemId> = ids.to_vec();
    sorted_ids.sort_by_key(|id| by_id[id].line_start);
    for id in sorted_ids {
        let it = by_id[&id];
        if matches!(it.kind, ItemKind::Use) {
            continue;
        }
        buf.push_str(&it.source);
        buf.push_str("\n\n");
    }
    buf
}
