use crate::item::{ItemId, ItemKind, ItemVis, ParsedItem};
use crate::promote::{
    CrossImport, add_pub_super, add_pub_super_to_fields, lift_impl_methods,
    rebase_body_super_for_subfile, rebase_pub_super_in_subfile,
};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

/// Render one `<bucket>.rs` body. Items are emitted in original source order
/// so the diff is easy to follow; `use` items are skipped here because they
/// already live in the shared prelude block at the top. Items whose id is
/// in `promote` are rewritten with a `pub(super)` visibility prefix.
/// `imports` carries the explicit `use super::<src>::<name>;` lines this
/// bucket needs so the bare-name references to *promoted* items in other
/// sub-buckets still resolve (since `pub use <bkt>::*;` only re-exports
/// `pub` items, the wildcard chain doesn't reach `pub(super)` items).
pub fn render_sub_file(
    ids: &[ItemId],
    by_id: &BTreeMap<ItemId, &ParsedItem>,
    use_prelude: &str,
    promote: &BTreeSet<ItemId>,
    impl_lifts: &BTreeSet<ItemId>,
    field_lifts: &BTreeSet<ItemId>,
    imports: &BTreeSet<CrossImport>,
) -> String {
    let mut buf = String::new();
    buf.push_str("// Auto-generated by r2factor. Manual edits will be overwritten on next split.\n\n");
    // Sibling refs flow through the facade's re-exports for `pub` items;
    // promoted `pub(super)` items need the explicit imports below.
    buf.push_str("use super::*;\n");
    if !use_prelude.is_empty() {
        buf.push_str(use_prelude);
        buf.push('\n');
    }
    for imp in imports {
        // Carry over any cfg attrs the target item had so the use line
        // doesn't try to resolve a symbol that's cfg'd-out for the
        // current target (E0432 otherwise).
        for cfg in &imp.cfg_attrs {
            let _ = writeln!(buf, "{cfg}");
        }
        let _ = writeln!(
            buf,
            "use super::{src}::{name};",
            src = imp.source_bucket,
            name = imp.name
        );
    }
    buf.push('\n');

    let mut sorted_ids: Vec<ItemId> = ids.to_vec();
    sorted_ids.sort_by_key(|id| by_id[id].line_start);
    for id in sorted_ids {
        let it = by_id[&id];
        if matches!(it.kind, ItemKind::Use) {
            continue;
        }
        // 1) Apply the relevant *visibility* transform (item-keyword level).
        let after_vis = if promote.contains(&id) {
            // `add_pub_super` handles both keyword AND fields, so skip the
            // separate field lift below for this branch.
            add_pub_super(&it.source)
        } else if impl_lifts.contains(&id) {
            lift_impl_methods(&it.source)
        } else if it.vis == ItemVis::Super {
            // Original `pub(super)` items now live one module deeper;
            // rebase to `pub(in super::super)` to preserve their scope.
            rebase_pub_super_in_subfile(&it.source)
        } else {
            it.source.clone()
        };
        // 2) Field-only lift for structs/unions that already had enough
        //    type-level visibility (so weren't in `promote`) but whose
        //    private fields would now be cross-bucket-invisible.
        let after_fields = if field_lifts.contains(&id) {
            add_pub_super_to_fields(&after_vis)
        } else {
            after_vis
        };
        // 3) Rebase relative `super::` paths in expressions/types/etc.
        //    Sub-files are one module-level deeper than the original, so
        //    `super::foo()` in the body needs to become
        //    `super::super::foo()`. Visibility paths are skipped by the
        //    visitor so the steps above are not double-rewritten.
        let final_src = rebase_body_super_for_subfile(&after_fields);
        buf.push_str(&final_src);
        buf.push_str("\n\n");
    }
    buf
}
