use crate::item::{ItemId, ItemKind, ItemVis, ParsedItem};
use crate::promote::{add_pub_super, lift_impl_methods, rebase_pub_super_in_subfile};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

/// Render one `<bucket>.rs` body. Items are emitted in original source order
/// so the diff is easy to follow; `use` items are skipped here because they
/// already live in the shared prelude block at the top. Items whose id is
/// in `promote` are rewritten with a `pub(super)` visibility prefix.
/// `imports` carries the explicit `use super::<src>::<name>;` lines this
/// bucket needs so the bare-name references to *promoted* items in other
/// sub-buckets still resolve (since `pub use <bkt>::*;` only re-exports
/// `pub` items, the wildcard chain doesn't reach `pub(super)` items).
pub fn render_sub_file(
    ids: &[ItemId],
    by_id: &BTreeMap<ItemId, &ParsedItem>,
    use_prelude: &str,
    promote: &BTreeSet<ItemId>,
    impl_lifts: &BTreeSet<ItemId>,
    imports: &BTreeSet<(String, String)>,
) -> String {
    let mut buf = String::new();
    buf.push_str("// Auto-generated by r2factor. Manual edits will be overwritten on next split.\n\n");
    // Sibling refs flow through the facade's re-exports for `pub` items;
    // promoted `pub(super)` items need the explicit imports below.
    buf.push_str("use super::*;\n");
    if !use_prelude.is_empty() {
        buf.push_str(use_prelude);
        buf.push('\n');
    }
    for (src_bucket, name) in imports {
        let _ = writeln!(buf, "use super::{src_bucket}::{name};");
    }
    buf.push('\n');

    let mut sorted_ids: Vec<ItemId> = ids.to_vec();
    sorted_ids.sort_by_key(|id| by_id[id].line_start);
    for id in sorted_ids {
        let it = by_id[&id];
        if matches!(it.kind, ItemKind::Use) {
            continue;
        }
        if promote.contains(&id) {
            buf.push_str(&add_pub_super(&it.source));
        } else if impl_lifts.contains(&id) {
            buf.push_str(&lift_impl_methods(&it.source));
        } else if it.vis == ItemVis::Super {
            // Original `pub(super)` items now live one module deeper;
            // rebase to `pub(in super::super)` to preserve their scope.
            buf.push_str(&rebase_pub_super_in_subfile(&it.source));
        } else {
            buf.push_str(&it.source);
        }
        buf.push_str("\n\n");
    }
    buf
}
