use crate::item::{ItemId, ItemKind, ParsedItem};
use crate::plan::Plan;
use anyhow::{Context, Result, anyhow, bail};
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

pub struct WriteOptions {
    pub force: bool,
}

#[derive(Debug)]
pub struct WriteReport {
    pub backup: PathBuf,
    pub target_dir: PathBuf,
    pub written_files: Vec<PathBuf>,
    pub facade: PathBuf,
}

pub fn write_plan(
    original: &Path,
    plan: &Plan,
    items: &[ParsedItem],
    opts: &WriteOptions,
) -> Result<WriteReport> {
    let parent = original.parent().unwrap_or(Path::new("."));
    let stem = original
        .file_stem()
        .and_then(|s| s.to_str())
        .ok_or_else(|| anyhow!("invalid file stem in {}", original.display()))?;
    if matches!(stem, "lib" | "main" | "mod") {
        bail!(
            "splitting `{stem}.rs` is not supported in v0 — choose a regular module file",
        );
    }
    let target_dir = parent.join(stem);
    if target_dir.exists() && !opts.force {
        bail!(
            "target dir {} already exists; pass --force to overwrite",
            target_dir.display()
        );
    }

    // 1) Backup FIRST. If this fails, we abort with no destruction.
    let backup = make_backup_path(original)?;
    fs::copy(original, &backup).with_context(|| {
        format!(
            "backup {} -> {}",
            original.display(),
            backup.display()
        )
    })?;

    // 2) Source preamble: inner attrs/doc-mod comments, plus the file's `use`s.
    let by_id: BTreeMap<ItemId, &ParsedItem> = items.iter().map(|i| (i.id, i)).collect();
    let original_src = fs::read_to_string(original)?;
    let inner_attrs = extract_inner_attrs(&original_src);
    let use_prelude: String = items
        .iter()
        .filter(|i| matches!(i.kind, ItemKind::Use))
        .map(|i| i.source.clone())
        .collect::<Vec<_>>()
        .join("\n");

    // 3) Sub-files.
    fs::create_dir_all(&target_dir)
        .with_context(|| format!("mkdir {}", target_dir.display()))?;

    let mut written: Vec<PathBuf> = Vec::new();
    let mut sub_modules: Vec<String> = Vec::new();
    let mut facade_uses: Vec<&ParsedItem> = Vec::new();
    // A bucket whose name equals the file stem holds the "primary" type for
    // this module — keep those items inline in the facade instead of pushing
    // them down into `<stem>/<stem>.rs`.
    let mut facade_primary: Vec<&ParsedItem> = Vec::new();

    for (module, ids) in &plan.assignments {
        if module == "mod_root" {
            for id in ids {
                facade_uses.push(by_id[id]);
            }
            continue;
        }
        if module == stem {
            for id in ids {
                facade_primary.push(by_id[id]);
            }
            continue;
        }
        let path = target_dir.join(format!("{module}.rs"));
        let body = render_sub_file(module, ids, &by_id, &use_prelude);
        fs::write(&path, body).with_context(|| format!("write {}", path.display()))?;
        written.push(path);
        sub_modules.push(module.clone());
    }
    sub_modules.sort();

    // If no sub-files were actually produced (everything ended up primary or
    // mod_root), drop the empty target dir to keep the tree clean.
    if sub_modules.is_empty()
        && let Err(e) = fs::remove_dir(&target_dir)
    {
        // Non-fatal: the dir may contain unrelated files.
        eprintln!(
            "[write] warn: could not remove unused target dir {}: {e}",
            target_dir.display()
        );
    }

    // 4) Facade: replace the original file.
    let facade_body = render_facade(&inner_attrs, &facade_uses, &facade_primary, &sub_modules);
    fs::write(original, facade_body)
        .with_context(|| format!("write facade {}", original.display()))?;

    Ok(WriteReport {
        backup,
        target_dir,
        written_files: written,
        facade: original.to_path_buf(),
    })
}

fn render_sub_file(
    module: &str,
    ids: &[ItemId],
    by_id: &BTreeMap<ItemId, &ParsedItem>,
    use_prelude: &str,
) -> String {
    let mut buf = String::new();
    buf.push_str("// Auto-generated by r2factor. Manual edits will be overwritten on next split.\n\n");
    // Sibling refs flow through the facade's re-exports.
    buf.push_str("use super::*;\n");
    if !use_prelude.is_empty() {
        buf.push_str(use_prelude);
        buf.push('\n');
    }
    buf.push('\n');

    let mut sorted_ids: Vec<ItemId> = ids.to_vec();
    sorted_ids.sort_by_key(|id| by_id[id].line_start);
    for id in sorted_ids {
        let it = by_id[&id];
        if matches!(it.kind, ItemKind::Use) {
            // already in the prelude
            continue;
        }
        buf.push_str(&it.source);
        buf.push_str("\n\n");
        let _ = module;
    }
    buf
}

fn render_facade(
    inner_attrs: &str,
    facade_uses: &[&ParsedItem],
    facade_primary: &[&ParsedItem],
    sub_modules: &[String],
) -> String {
    let mut buf = String::new();
    if !inner_attrs.is_empty() {
        buf.push_str(inner_attrs);
        buf.push_str("\n\n");
    }
    buf.push_str("// Auto-generated by r2factor. Manual edits will be overwritten on next split.\n\n");

    for it in facade_uses {
        buf.push_str(&it.source);
        buf.push('\n');
    }
    if !facade_uses.is_empty() {
        buf.push('\n');
    }

    for m in sub_modules {
        if m == "tests" {
            buf.push_str(&format!("#[cfg(test)]\nmod {m};\n"));
        } else {
            buf.push_str(&format!("mod {m};\n"));
        }
    }
    if !sub_modules.is_empty() {
        buf.push('\n');
    }

    for m in sub_modules {
        if m == "tests" {
            continue;
        }
        buf.push_str(&format!("pub use {m}::*;\n"));
    }
    if !sub_modules.iter().all(|m| m == "tests") {
        buf.push('\n');
    }

    // Primary items live in the facade itself — they're the main thing this
    // file is "about", and pushing them into <stem>/<stem>.rs would create
    // an awkward duplicated path.
    let mut primary_sorted: Vec<&&ParsedItem> = facade_primary.iter().collect();
    primary_sorted.sort_by_key(|it| it.line_start);
    for it in primary_sorted {
        buf.push_str(&it.source);
        buf.push_str("\n\n");
    }
    buf
}

fn make_backup_path(original: &Path) -> Result<PathBuf> {
    let ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let mut path = original.to_path_buf();
    let name = original
        .file_name()
        .and_then(|s| s.to_str())
        .ok_or_else(|| anyhow!("invalid filename {}", original.display()))?;
    path.set_file_name(format!("{name}.r2factor.bak.{ts}"));
    Ok(path)
}

fn extract_inner_attrs(src: &str) -> String {
    let mut out = String::new();
    for line in src.lines() {
        let t = line.trim_start();
        if t.is_empty() || t.starts_with("//!") || t.starts_with("#![") {
            out.push_str(line);
            out.push('\n');
        } else {
            break;
        }
    }
    out.trim_end().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extract_inner_attrs_finds_doc_mod() {
        let src = "//! file-level doc\n//! more docs\n\nuse foo::bar;\nfn x() {}";
        let out = extract_inner_attrs(src);
        assert_eq!(out, "//! file-level doc\n//! more docs");
    }

    #[test]
    fn extract_inner_attrs_handles_inner_attr() {
        let src = "#![allow(dead_code)]\n//! doc\nfn x(){}";
        let out = extract_inner_attrs(src);
        assert_eq!(out, "#![allow(dead_code)]\n//! doc");
    }

    #[test]
    fn extract_inner_attrs_returns_empty_when_none() {
        assert_eq!(extract_inner_attrs("fn x(){}"), "");
    }

    #[test]
    fn backup_path_appends_timestamp() {
        let p = make_backup_path(Path::new("/tmp/foo.rs")).unwrap();
        let s = p.to_string_lossy();
        assert!(s.starts_with("/tmp/foo.rs.r2factor.bak."));
    }
}
